from .digits_multiplication import test_digits_multiplication
from .fibonacci import solve_fibonacci_task
from .palindrome import is_palindrome
from .the_longest_word import solve_the_longest_word_task
